### PR TITLE
Privacy update

### PR DESCRIPTION
**Pull request by nonchris**
Until now the task uuids were just directly logged, which meant that they were available to anyone with access to the logs.  

This PR introduces UUID obfuscation, so that the actual UUIDs are not visible in the log.

Example of an obfuscated uuid `<task_uuid: ab1e...563b>`.  
A part of the uuid is still shown to provide a coherent and understandable log, whilst providing better data privacy.

### What's new?
All described "hide uuid features" are only active when the env variable is set!
* A new environment variable, `LOG_PRIVACY_MODE` (now active by default) activates the feature
* A new BaseClass is introduced that automatically hides UUIDs from calls to `str` and `repr` 
* A new function in `log_setup` called `uuid_log_format(uuid)` is used to hide all uuids in logs  

#### Other new things / fixes
* The logs for processed requests are now closely matching the ones from uvicorn
  * uvicorns own logs are now set to warning instead of debug
* Some minor tweaks to general logs 
* An issue that some logs didn't follow the correct log format was (hopefully) fixed
* Readme has a better overview of the features of this project

### CODE REVIEW

**Comment by nonchris** [comment]
@MayNiklas the change to uvicorns log level to warning++ is only set inside `main.py` and only active when executing the package directly.   
Which is the way I use for development.  
Are there any places in the docs where we call the thing in a different way so that we might need an additional flag to set uvicors log level to warning?

**Comment by MayNiklas** [comment]
Different ways of executing the API are only relevant for development.
I would argue, that we don't have to think too much about privacy during development...

**Comment by nonchris** [comment]
That wasn't the main point. During development thats pretty irrelevant.  
I was more concerned over the ways we suggested for actual deployment.  
You can call uvicorn from the command line and pass the FastAPI object directly which would lead to a bypass of the start function that configures uvicorns logs. Thats why I wondered if we need to adjust a CLI flag somewhere in our docs.

**Review by MayNiklas — APPROVED** [review]
👍 Thanks for the improvement!

**Pull request merged**
